In [1]:
import bisect
import pandas as pd
import json
# a: the original whole set list
# b: the 6060 dev set list
df_a = pd.read_json("/home/jiaruil5/multilingual/multilingual-model-card/src/dictionary_collection/growing_dict/mturk.json").sort_values(by='English')
df_a['source'] = "whole"
df_b = pd.read_csv("/home/jiaruil5/multilingual/multilingual-model-card/src/dictionary_collection/mturk/terminology_from_6060.csv")

# get context of b
context_b = [i.strip() for i in open("/home/jiaruil5/multilingual/multilingual-model-card/src/data_eval_6060/2/acl_6060/dev/text/tagged_terminology/ACL.6060.dev.tagged.en-xx.en.txt", 'r').readlines()]
df_b_upd_lst = []
for idx, row in df_b.iterrows():
    term = row['english']
    context_str_lst = []
    for context in context_b:
        if f"[{term}]" in context:
            context = context.replace("[", "")
            context = context.replace("]", "")
            context = context.replace(term, f"<mark>{term}</mark>")
            context_str_lst.append(context.strip())
    context_str = "<br>".join([f"{i+1}: " + item for i, item in enumerate(context_str_lst[:3])]) + "<br>"
    new_info = {
        "English": term,
        "context": context_str,
        "Arabic": row['arabic'],
        "Chinese": row['chinese'],
        "French": row['french'],
        "Japanese": row['japanese'],
        "Russian": row['russian'],
        "source": "6060"
    }
    df_b_upd_lst.append(new_info)
df_b_upd = pd.DataFrame().from_records(df_b_upd_lst)

In [2]:
a = df_a.to_dict(orient='records')
b = df_b_upd.to_dict(orient='records')

In [3]:
import heapq
a.sort(key=lambda x: x['English'])
b.sort(key=lambda x: x['English'])

# Merge the two sorted lists
merged = list(heapq.merge(a, b, key=lambda x: x['English']))

In [4]:
merged

[{'English': '10-fold cross validation',
  'context': "1: For all the methods, we used <mark>10-fold cross validation</mark> (i.e., each fold we have 556 training and 62 test samples) to tune free parameters, e.g., the kernel form and parameters for GPOR and LapSVM. Note that all the alternative methods stack X and Z together into a whole data matrix and ignore their heterogeneous nature.<br>2: Features associated one-to-one with a vertical (Clarity, ReDDE, the query likelihood given the vertical's query-log and Soft.ReDDE) were normalized across verticals before scaling. Supervised training/testing was done via <mark>10-fold cross validation</mark>. Parameter τ was tuned for each training fold on the same 500 query validation set used for our single feature baselines.<br>",
  'Arabic': 'التحقق المتقاطع بمقدار ١٠ أضعاف',
  'Chinese': '十折交叉验证',
  'French': 'validation croisée 10 fois',
  'Japanese': '10分割交差検証',
  'Russian': '10-кратная перекрестная проверка',
  'source': 'whole'},
 {'English': '1D convolution',
  'context': '1: In addition to the usual quadratic kernels we also apply kernels that only span the pitch dimension and are supposed to detect overtones and harmonies (see Table 1). The autoregressive model is a ResNet as well, but with <mark>1D convolution</mark>s (Table 2).<br>',
  'Arabic': '1D الإلتواء',
  'Chinese': '1D 卷积',
  'French': 'Convolution 1D',
  'Japanese': '1次元畳み込み',
  'Russian': 'одномерная свертка',
  'source': 'whole'},
 {'English': '2 norm',
  'context': '1: To alleviate this limitation, we proposed a new algorithm called Clippy. Clippy has two major changes over GC/AGC: First, it uses ∞ norm instead of <mark>2 norm</mark> to increase its sensitivity to changes in individual coordinates.<br>2: Finally, CoCL computes the following average: \n L CoCL = 1 |C| c∈C l c , \n where • is the <mark>2 norm</mark>.<br>',
  'Arabic': 'معيار 2',
  'Chinese': '2范数',
  'French': 'norme 2',
  'Japanese': '2ノルム',
  'Russian': '2 норма',
  'source': 'whole'},
 {'English': '2D convolution',
  'context': '1: Adding 3D convolutions to <mark>2D convolution</mark>s essentially leads to a design similar to Top-Heavy S3D architecture [73], which shows better performance than full 3D convolutions on video action recognition and runs faster. Results are shown in Table 2. Overall, models that use 3D convolutions perform worse than models that adopt a simple mean pooling.<br>2: by moving it closer to a surface, the 2D neighborhood of a feature may change. As a result, <mark>2D convolution</mark>s come with no guarantee on multiview consistency. With our per-pixel formulation, the rendering function Θ operates independently on all pixels, allowing images to be generated with arbitrary resolutions and poses.<br>',
  'Arabic': 'الإلتواء 2D',
  'Chinese': '二维卷积',
  'French': 'convolution 2D',
  'Japanese': '2D畳み込み',
  'Russian': '2D свертка',
  'source': 'whole'},
 {'English': '2D image',
  'context': '1: Here x is the feature computed by a layer, and i is an index. In the case of <mark>2D image</mark>s, i \n = (i N , i C , i H , i W ) is a 4D vec- tor indexing the features in (N, C, H, W ) order, \n<br>',
  'Arabic': 'صورة ثنائية الأبعاد',
  'Chinese': '二维图像',
  'French': 'image 2D',
  'Japanese': '2次元画像',
  'Russian': '2D изображение',
  'source': 'whole'},
 {'English': '2D image synthesis',
  'context': '1: Neural Image Synthesis. Deep models for 2D image and video synthesis have recently shown promising results in generating photorealistic images.<br>',
  'Arabic': 'تخليق صور ثنائية الأبعاد',
  'Chinese': '二维图像合成',
  'French': "synthèse d'images 2D",
  'Japanese': '2次元画像合成',
  'Russian': 'синтез 2D-изображений',
  'source': 'whole'},
 {'English': '2D-3D correspondence',
  'context': '1: To summarize, our main contributions are as follows: \n • We propose the EPro-PnP, a probabilistic PnP layer for general end-to-end pose estimation via learnable <mark>2D-3D correspondence</mark>s. • We demonstrate that EPro-PnP can easily reach toptier performance for 6DoF pose estimation by simply inserting it into the CDPN [29] framework.<br>2: • We demonstrate the flexibility of EPro-PnP by proposing deformable correspondence learning for accurate 3D object detection, where the entire <mark>2D-3D correspondence</mark>s are learned from scratch.<br>',
  'Arabic': 'المراسلات ثنائية وثلاثية الأبعاد',
  'Chinese': '二维三维对应关系',
  'French': 'correspondances 2d-3d',
  'Japanese': '2次元-3次元対応',
  'Russian': '2D-3D соответствие',
  'source': 'whole'},
 {'English': '3D bounding box',
  'context': '1: The subset of PASCAL we considered after filtering occluded instances, which we do not tackle in this paper, had between 70 images for "sofa" and 500 images for classes "aeroplanes" and "cars". We will make all our image sets available along with our implementation. Metrics. We quantify the quality of our 3D models by comparing against the PASCAL 3D+ models using two metrics -1 ) the Hausdorff distance normalized by the <mark>3D bounding box</mark> size of the ground truth model [ 3 ] and 2 ) a depth map error to evaluate the quality of the reconstructed visible object surface , measured as the mean absolute distance between reconstructed<br>2: For an individual asset, we annotate its object type, computationally obtain its <mark>3D bounding box</mark>, and partition assets of object types into training, validation, and testing splits. Then, we annotate how each object type might be spawned into the house.<br>',
  'Arabic': 'صندوق احتواء ثلاثي الأبعاد',
  'Chinese': '三维包围盒',
  'French': 'boîte englobante 3D',
  'Japanese': '3次元バウンディングボックス',
  'Russian': '3D ограничивающий параллелепипед',
  'source': 'whole'},
 {'English': '3D computer vision',
  'context': '1: Point cloud registration (PCR) is an important and fundamental problem in <mark>3D computer vision</mark> and has a wide range of applications in localization [13], 3D object detection [17] and 3D reconstruction [25].<br>',
  'Arabic': 'الرؤية الحاسوبية ثلاثية الأبعاد',
  'Chinese': '三维计算机视觉',
  'French': 'Vision par ordinateur 3D',
  'Japanese': '3次元コンピュータビジョン',
  'Russian': 'трехмерное компьютерное зрение',
  'source': 'whole'},
 {'English': '3D convolutional network',
  'context': '1: The choice of architecture proves to be important for performance, with <mark>3D convolutional network</mark>s excelling at tasks involving complex geometries, graph networks performing well on systems requiring detailed positional information, and the more recently developed equivariant networks showing significant promise.<br>',
  'Arabic': 'شبكة تلافيفية ثلاثية الأبعاد',
  'Chinese': '三维卷积网络',
  'French': 'réseau convolutionnel 3D',
  'Japanese': '3次元畳み込みネットワーク',
  'Russian': 'трёхмерная сверточная сеть',
  'source': 'whole'},
 {'English': '3D geometry',
  'context': '1: To that end we define an energy function that assigns each pixel to a segment and each segment to the <mark>3D geometry</mark> and motion of a plane. This allows us to estimate the 3D scene flow and depth for every pixel of a reference view.<br>2: Previous work on new-view synthesis or stereo reconstruction has typically included such prior knowledge as a priori constraints on the (piecewise) smoothness of the <mark>3D geometry</mark>, which results in artifacts at depth boundaries.<br>',
  'Arabic': 'هندسة ثلاثية الأبعاد',
  'Chinese': '三维几何',
  'French': 'géométrie 3D',
  'Japanese': '3次元ジオメトリ',
  'Russian': '3D геометрия',
  'source': 'whole'},
 {'English': '3D human pose estimation',
  'context': '1: Existing diffusion-based pose estimation approaches [10,17,21,42] have been used mainly for <mark>3D human pose estimation</mark>, which regresses the locations of 3D keypoints of humans from 2D RGB images of the human body. This is because the uncertain 2D-to-3D lifting can be modeled as a probability distribution.<br>2: We developed a Picture program for parsing 3D pose of articulated humans from single images. There has been notable work in model-based approaches [13,27] for <mark>3D human pose estimation</mark>, which served as an inspiration for the program we describe in this section.<br>',
  'Arabic': 'تقدير وضعية الإنسان ثلاثي الأبعاد',
  'Chinese': '三维人体姿态估计',
  'French': 'estimation de la pose humaine en 3D',
  'Japanese': '3次元人体姿勢推定',
  'Russian': 'оценка позы человека в 3D',
  'source': 'whole'},
 {'English': '3D localization',
  'context': '1: After being processed by the subsequent layers, the object-level features are finally transformed into to the object-level predictions, consisting of the <mark>3D localization</mark> score, weight scale, 3D bounding box size, and other optional properties (velocity and attribute).<br>',
  'Arabic': 'التحديد ثلاثي الأبعاد',
  'Chinese': '三维定位',
  'French': 'Localisation 3D',
  'Japanese': '3次元位置推定',
  'Russian': '3D локализация',
  'source': 'whole'},
 {'English': '3D mesh',
  'context': '1: * Authors contributed equally Figure 1: Automatic object reconstruction from a single image obtained by our system. Our method leverages estimated instance segmentations and predicted viewpoints to generate a full <mark>3D mesh</mark> and high frequency 2.5D depth maps. PASCAL VOC [15]).<br>',
  'Arabic': 'شبكة ثلاثية الأبعاد',
  'Chinese': '3D网格',
  'French': 'maillage 3D',
  'Japanese': '3次元メッシュ',
  'Russian': '3D сетка',
  'source': 'whole'},
 {'English': '3D model',
  'context': '1: The 3D flow algorithm of §6 was initialized with 100 points on the face found by an interest operator in a single frame, and successfully found correspondences across the entire sequence, concluding with a corrective transform to give the <mark>3D model</mark> used to generate the images in figure 6. Figure 5 shows the recovered motion parameters.<br>2: A <mark>3D model</mark> consists of 3D points X, cameras C, and relation I ⊂ X × C encoding observations ((X m , C i ) ∈ I iff C i observes X m ). For Scranton, we may sample a single p-s pair (p, s) ∈ M as follows: \n 1.<br>',
  'Arabic': 'نموذج ثلاثي الأبعاد',
  'Chinese': '三维模型',
  'French': 'modèle 3D',
  'Japanese': '3Dモデル',
  'Russian': '3D-модель',
  'source': 'whole'},
 {'English': '3D object detection',
  'context': '1: Estimating the pose (i.e., position and orientation) of 3D objects from a single RGB image is an important task in computer vision. This field is often subdivided into specific tasks, e.g., 6DoF pose estimation for robot manipulation and <mark>3D object detection</mark> for autonomous driving.<br>2: Although they share the same fundamentals of pose estimation, the different nature of the data leads to biased choice of methods. Top performers [34,48,50] on the <mark>3D object detection</mark> benchmarks [8,17] fall into the category of direct 4DoF pose prediction, leveraging the advances in end-toend deep learning.<br>',
  'Arabic': 'اكتشاف الكائنات ثلاثية الأبعاد',
  'Chinese': '三维目标检测',
  'French': "détection d'objets 3D",
  'Japanese': '3次元物体検出',
  'Russian': 'обнаружение 3D-объектов',
  'source': 'whole'},
 {'English': '3D point',
  'context': '1: An analogous warping is used for non-rigid tracking [37] without the part based representation, which allows mapping between consecutive frames. With the part based warping, we substantially extend the time horizon by parametrizing the <mark>3D point</mark> using the UV coordinate, which does not require an offline iterative closest point method between the consecutive frames.<br>',
  'Arabic': 'نقطة ثلاثية الأبعاد',
  'Chinese': '三维点',
  'French': 'point 3D',
  'Japanese': '3次元点',
  'Russian': '3D точка',
  'source': 'whole'},
 {'English': '3D point cloud',
  'context': '1: In Figure 6, for each scene we show column by column an image-like view of the event streams, estimated gradient map, reconstructed intensity map with super resolution and high dynamic range properties, estimate depth map and semi-dense <mark>3D point cloud</mark>.<br>2: Given input features of 2D images, pixels are projected onto a 3D permutohedral lattice defined by 3D positional lattice features. The splatted signal is then sliced onto the points of interest in a <mark>3D point cloud</mark>. BCL 3D→2D . Sometimes, we are also interested in segmenting 2D images and want to leverage relevant 3D information for better 2D segmentation.<br>',
  'Arabic': 'سحابة نقاط ثلاثية الأبعاد',
  'Chinese': '三维点云',
  'French': 'nuage de points 3D',
  'Japanese': '3D点群',
  'Russian': 'облако точек 3D',
  'source': 'whole'},
 {'English': '3D pose',
  'context': '1: We developed a Picture program for parsing <mark>3D pose</mark> of articulated humans from single images. There has been notable work in model-based approaches [13,27] for 3D human pose estimation, which served as an inspiration for the program we describe in this section.<br>',
  'Arabic': 'وضعية ثلاثية الأبعاد',
  'Chinese': '三维姿势',
  'French': 'pose 3D',
  'Japanese': '3次元ポーズ',
  'Russian': '3D поза',
  'source': 'whole'},
 {'English': '3D reconstruction',
  'context': '1: Minimal problems arise from geometrical problems in <mark>3D reconstruction</mark> [59,61,62], image matching [55], visual oodometry,and localization [3,49,57,66].<br>2: Accurately finding dense correspondence between images capturing deforming objects is important for many vision tasks, such as <mark>3D reconstruction</mark>, image alignment and tracking. However, estimating the parameters of nonrigid deformation is hard due to its high-dimensionality and strong nonconvexity. Continuous optimization approaches (e.g.<br>',
  'Arabic': 'إعادة الإعمار ثلاثية الأبعاد',
  'Chinese': '三维重建',
  'French': 'reconstruction 3D',
  'Japanese': '3D再構築',
  'Russian': 'Трехмерная реконструкция',
  'source': 'whole'},
 {'English': '3D scene',
  'context': '1: Since most current scene understanding approaches operate either on the 2D image or using a surface-based representation, they do not allow reasoning about the physical constraints within the <mark>3D scene</mark>.<br>',
  'Arabic': 'المشهد ثلاثي الأبعاد',
  'Chinese': '三维场景',
  'French': 'scène 3D',
  'Japanese': '3次元シーン',
  'Russian': 'трёхмерная сцена',
  'source': 'whole'},
 {'English': '3D scene geometry',
  'context': '1: However, exhaustive sampling of the light field is impractical in most scenarios, so methods for view synthesis from sparsely-captured images reconstruct <mark>3D scene geometry</mark> in order to reproject observed images into novel viewpoints [7]. For scenes with glossy surfaces, some methods explicitly build virtual geometry to explain the motion of reflections [15,31,33].<br>2: ments required for scene understanding: low-level object detectors, rough <mark>3D scene geometry</mark>, and approximate camera position/orientation. Our main insight is to model the contextual relationships between the visual elements, not in the 2D image plane where they have been projected by the camera, but within the 3D world where they actually reside.<br>',
  'Arabic': 'هندسة المشهد ثلاثية الأبعاد',
  'Chinese': '3D场景几何',
  'French': 'géométrie de la scène 3D',
  'Japanese': '3次元シーンジオメトリ',
  'Russian': 'геометрия 3D сцены',
  'source': 'whole'},
 {'English': '3D structure',
  'context': '1: This issue was either ignored by researchers 8, 4, 1, 7], or else was addressed using other minimization approaches 3,5]. Morris and Kanade 3] have suggested a uni ed approach for recovering the <mark>3D structure</mark> and motion from point and line features, by taking into account t h e i r directional uncertainty.<br>',
  'Arabic': 'البنية ثلاثية الأبعاد',
  'Chinese': '三维结构',
  'French': 'structure 3D',
  'Japanese': '3次元構造',
  'Russian': '3D структура',
  'source': 'whole'},
 {'English': '5-fold cross validation',
  'context': '1: The results were obtained using <mark>5-fold cross validation</mark>, where 4 5 of the 94 images were used to train the CRF pa-   rameters. The unary potentials were learned on a separate training set that did not include the 94 accurately annotated images. We also adopt the methodology proposed by Kohli et al.<br>',
  'Arabic': '"التقسيم المتقاطع الخماسي"',
  'Chinese': '5重交叉验证',
  'French': 'Validation croisée à 5 volets',
  'Japanese': '5分割交差検証',
  'Russian': '5-кратная перекрестная проверка',
  'source': 'whole'},
 {'English': 'A * algorithm',
  'context': '1: On line 6, a BDD representing all closed states is constructed. The while-cycle on lines 7-16 is an <mark>A * algorithm</mark> adapted to the symbolic search. On line 8, we extract the set of states with the lowest f -value from the open list and remove all closed states from this set.<br>2: The basic <mark>A * algorithm</mark> operates on deduction items I(A, i, j) which represent in a collapsed way the possible inside derivations of edges (A, i, j).<br>',
  'Arabic': '"الگوريتم A*"',
  'Chinese': 'A*算法',
  'French': 'algorithme A*',
  'Japanese': 'A*アルゴリズム',
  'Russian': 'Алгоритм A*',
  'source': 'whole'},
 {'English': 'A/B test',
  'context': '1: eg : <mark>A/B test</mark>s ) vs absolute evaluation ( eg : Likert ) , which has been discussed in Tang et al . (2022) for short-form news summarization datasets like CNN/DM. Our paper is limited to faithfulness evaluation, but summaries are typically evaluated for salience, fluency, coherence as well (Fabbri et al., 2021).<br>',
  'Arabic': 'اختبار أ/ب',
  'Chinese': 'A/B测试',
  'French': 'test A/B',
  'Japanese': 'A/Bテスト',
  'Russian': 'тест A / B',
  'source': 'whole'},
 {'English': 'A2C',
  'context': '1: [10] -using the same architectures and task paradigm, but here the agent is trained with PPO instead of <mark>A2C</mark>. Having established that humans and agents seem to use different representations to perform these tasks -presumably driven by differences in inductive bias -we now consider how to provide the agent with more human-like inductive bias(es).<br>',
  'Arabic': 'a2c',
  'Chinese': 'A2C',
  'French': 'A2C',
  'Japanese': 'A2C',
  'Russian': 'а2с',
  'source': 'whole'},
 {'English': 'AI',
  'context': '1: A work done at Applica <mark>AI</mark> in cooperation with Lukasz Borchmann and Lukasz Garncarek.<br>',
  'Arabic': 'AI',
  'Chinese': '人工智能',
  'French': 'intelligence artificielle',
  'Japanese': 'AI',
  'Russian': 'AI',
  'source': '6060'},
 {'English': 'API',
  'context': '<br>',
  'Arabic': 'API',
  'Chinese': 'API',
  'French': 'API',
  'Japanese': 'API',
  'Russian': 'API',
  'source': '6060'},
 {'English': 'AQA',
  'context': '1: Apart from the three datasets <mark>AQA</mark>, AmbigQA and QUOREF-Contrast set that are already available, we also evaluate on RGF counterfactuals that are paired with original NQ questions based on whether they underwent a predicate change or reference change.<br>',
  'Arabic': 'AQA',
  'Chinese': 'AQA',
  'French': 'AQA',
  'Japanese': 'AQA',
  'Russian': 'AQA',
  'source': '6060'},
 {'English': 'ARENA',
  'context': '<br>',
  'Arabic': 'ARENA',
  'Chinese': 'ARENA',
  'French': 'ARENA',
  'Japanese': 'ARENA',
  'Russian': 'ARENA',
  'source': '6060'},
 {'English': 'Ablation study',
  'context': '1: <mark>Ablation study</mark>: Table 4 shows the performance of several variants of our featuremetric optimization on ETH3D in terms of triangulation (scene Facade only) and localization (all scenes). We compare both types of adjustments, minor tweaks, and different image representations, including  Relative run times for 1000 images: \n Figure 3: Run-times.<br>2: <mark>Ablation study</mark> of PiCO on noisy partial label learning datasets CIFAR-10 (q = 0.5, η = 0.2) and CIFAR-100 (q = 0.05, η = 0.2).<br>',
  'Arabic': 'دراسة الاستئصال',
  'Chinese': '消融研究',
  'French': "étude d'ablation",
  'Japanese': 'アブレーション研究',
  'Russian': 'изучение аблации',
  'source': 'whole'},
 {'English': 'Accuracy',

In [4]:
df = pd.DataFrame().from_records(merged)

In [8]:
df.shape[0]

5027

In [12]:
df[df.duplicated(subset=['English'], keep=False)]

,English,context,Arabic,Chinese,French,Japanese,Russian,source
895,annotation,1: The '<mark>annotation</mark>' prompt contai...,تعليقات,标注,annotation,アノテーション,аннотация,whole
896,annotation,1: This could be done by human <mark>annotatio...,التعليق التوضيحي,注释,annotation,注釈,аннотация,6060
973,augmentation,1: zero mean unit variance Gaussian random var...,تكبير,增强,augmentation,拡張,усиление,whole
974,augmentation,"1: So, to effectively evaluate the effectivene...",زيادة,增强,élargissement,増大,увеличение,6060
1084,bidirectional,1: The placement of an information bottleneck ...,ثنائي الاتجاه,双向的,bidirectionnel,双方向性,двунаправленный,whole
...,...,...,...,...,...,...,...,...
4867,utterance,1: From the finish of the user <mark>utterance...,نُطقٍ,发声,énonciation,発話,высказывание,6060
4906,vector,1: Once we had learned a <mark>vector</mark> w...,المتجه,向量,vecteur,ベクトル,вектор,whole
4907,vector,1: The other option is to predict the affix pr...,متجه,向量,vectoriel,ベクトル,вектор,6060
4947,vocabulary,"1: For the En→De translation task, sentences a...",مفردات,词汇量,vocabulaire,語彙,словарь,whole
4948,vocabulary,1: In terms of NLP ah borrowings are a common ...,مفردات,词汇,vocabulaire,語彙,словарь,6060

In [10]:
df['English'].unique().shape

(4990,)

In [6]:
df.to_csv("/home/jiaruil5/multilingual/multilingual-model-card/src/dictionary_collection/mturk/mturk_with_6060.csv")

In [6]:
# df = df.sample(frac=1).reset_index(drop=True)

In [7]:
# chunk mturk
num_terms_per_hit = 10
# Create empty sub-dataframes
interleaved_sub_dfs = [df.iloc[i::num_terms_per_hit].reset_index(drop=True) for i in range(num_terms_per_hit)]

# Add suffixes to each interleaved sub-dataframe
suffixes = [str(i) for i in range(1, num_terms_per_hit+1)]
interleaved_sub_dfs = [sub_df.add_suffix(suffix) for sub_df, suffix in zip(interleaved_sub_dfs, suffixes)]

# Concatenate the interleaved sub-dataframes by columns
interleaved_concat_df = pd.concat(interleaved_sub_dfs, axis=1)

interleaved_concat_df

,English1,context1,Arabic1,Chinese1,French1,Japanese1,Russian1,source1,English2,context2,...,Russian9,source9,English10,context10,Arabic10,Chinese10,French10,Japanese10,Russian10,source10
0,10-fold cross validation,"1: For all the methods, we used <mark>10-fold ...",التحقق المتقاطع بمقدار ١٠ أضعاف,十折交叉验证,validation croisée 10 fois,10分割交差検証,10-кратная перекрестная проверка,whole,1D convolution,1: In addition to the usual quadratic kernels ...,...,трехмерное компьютерное зрение,whole,3D convolutional network,1: The choice of architecture proves to be imp...,شبكة تلافيفية ثلاثية الأبعاد,三维卷积网络,réseau convolutionnel 3D,3次元畳み込みネットワーク,трёхмерная сверточная сеть,whole
1,3D geometry,1: To that end we define an energy function th...,هندسة ثلاثية الأبعاد,三维几何,géométrie 3D,3次元ジオメトリ,3D геометрия,whole,3D human pose estimation,1: Existing diffusion-based pose estimation ap...,...,3D поза,whole,3D reconstruction,1: Minimal problems arise from geometrical pro...,إعادة الإعمار ثلاثية الأبعاد,三维重建,reconstruction 3D,3D再構築,Трехмерная реконструкция,whole
2,3D scene,1: Since most current scene understanding appr...,المشهد ثلاثي الأبعاد,三维场景,scène 3D,3次元シーン,трёхмерная сцена,whole,3D scene geometry,"1: However, exhaustive sampling of the light f...",...,API,6060,AQA,1: Apart from the three datasets <mark>AQA</ma...,AQA,AQA,AQA,AQA,AQA,6060
3,ARENA,<br>,ARENA,ARENA,ARENA,ARENA,ARENA,6060,Ablation study,1: <mark>Ablation study</mark>: Table 4 shows ...,...,Оптимизация Адама,whole,Adam optimization algorithm,1: This loss function is only used during trai...,خوارزمية التحسين آدم,Adam优化算法,algorithme d'optimisation Adam,Adamの最適化アルゴリズム,Алгоритм оптимизации Адама,whole
4,Adam optimizer,"1: Second, the <mark>Adam optimizer</mark> in ...",محسن آدم,Adam优化器,Optimiseur Adam,Adamオプティマイザ,Оптимизатор Адам,whole,Adapter,"1: In <mark>Adapter</mark>-based IPT, we set t...",...,аркадная обучающая среда,whole,Architectures,<br>,هياكل,架构,architectures,アーキテクチャ,Архитектуры,6060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,weight vector,"1: where n is the number of training examples,...",متجه الوزن,权重向量,vecteur de poids,重みベクトル,вектор весов,whole,weight-sharing,1: Siamese networks can naturally introduce in...,...,веса,6060,white-box,1: Next we employ them as the trigger to attac...,صندوق أبيض,白盒,boîte blanche,ホワイトボックス,белый ящик,whole
499,white-box attack,1: Defense-GAN was not shown to be effective o...,هجوم الصندوق الأبيض,白盒攻击,attaque en boîte blanche,ホワイトボックス攻撃,атака белого ящика,whole,window size,1: The performance of kb-SRK reaches the peak ...,...,представление слова,whole,word segmentation,1: We present an unsupervised <mark>word segme...,تجزئة الكلمة,词语分割,segmentation des mots,単語分割,сегментация слов,whole
500,word sense disambiguation,1: named entity recognition (Collins and Singe...,تمييز معنى الكلمة,词义消歧,désambiguïsation du sens des mots,単語意味の曖昧さ解消,разрешение неоднозначности слова,whole,word similarity,"1: In this paper, we describe design considera...",...,словарь на уровне слов,whole,word2vec,<br>,word2vec,word2vec,word2vec,単語2vec,word2vec,6060
501,word2vec embedding,1: The use of lexical semantic information in ...,تضمين word2vec,词向量嵌入,représentation word2vec,word2vecエンベディング,word2vec вложения,whole,words,"1: Well, lexical borrowing is basically the in...",...,нулевая межъязыковая настройка,whole,zero-shot generalization,1: We also observe that the EM of ArcaneQA on ...,التعميم الصفري,零样本泛化,généralisation zéro-shot,ゼロショット汎化,обобщение с нулевым выстрелом,whole
502,zero-shot learning,1: Existing deep learning-based approaches usu...,التعلم الصفري,零样本学习,"""apprentissage sans tir""",ゼロショット学習,обучение с нулевым выстрелом,whole,zero-shot prediction,"1: For ChatGPT, we slightly modify the prompts...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
interleaved_concat_df.to_csv("mturk_10terms_per_page_with_6060.csv")