In [1]:
import json
import pandas as pd
tgt_langs = [
    "Arabic",
    "Chinese",
    "French",
    "Japanese",
    "Russian",
]

In [2]:
models = ['nllb', 'seamless', 'gpt4omini', 'aya_old', 'aya']
# models = ['nllb']
# exp_dict = {"default": "_comet", "prompt": "_prompt_gpt4omini_comet", "replace": "_hard_replace_comet"}
exp_dict = {"default": "_comet", "prompt": "_prompt_gpt4omini_comet", "replace": "_hard_replace_comet", "replace_morphology": "_hard_replace_morphology_comet"}
for model in models:
    dataframe_dict = {}
    for exp_name, exp_suffix in exp_dict.items():
        column_name = f"{exp_name}_{model}"
        dataframe_dict[column_name] = []
        
        data = json.load(open(f"/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/data_eval_6060/eval/gold_predictions_dev_{model}{exp_suffix}.json"))
        for lang in tgt_langs:
            dataframe_dict[column_name].append(data.get(f"{lang}_system_score", 0))  # Use `.get()` with default value `0` if lang not found

    # Create the DataFrame
    df = pd.DataFrame(dataframe_dict, index=tgt_langs)
    print(df.to_latex(float_format="%.2f"))

\begin{tabular}{lrrrr}
\toprule
 & default_nllb & prompt_nllb & replace_nllb & replace_morphology_nllb \\
\midrule
Arabic & 0.84 & 0.84 & 0.83 & 0.85 \\
Chinese & 0.78 & 0.81 & 0.79 & 0.82 \\
French & 0.83 & 0.84 & 0.83 & 0.84 \\
Japanese & 0.78 & 0.82 & 0.78 & 0.83 \\
Russian & 0.81 & 0.82 & 0.80 & 0.83 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
 & default_seamless & prompt_seamless & replace_seamless & replace_morphology_seamless \\
\midrule
Arabic & 0.84 & 0.85 & 0.84 & 0.85 \\
Chinese & 0.83 & 0.85 & 0.84 & 0.86 \\
French & 0.84 & 0.85 & 0.84 & 0.85 \\
Japanese & 0.85 & 0.86 & 0.85 & 0.87 \\
Russian & 0.82 & 0.83 & 0.80 & 0.84 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
 & default_gpt4omini & prompt_gpt4omini & replace_gpt4omini & replace_morphology_gpt4omini \\
\midrule
Arabic & 0.86 & 0.86 & 0.85 & 0.86 \\
Chinese & 0.87 & 0.88 & 0.88 & 0.88 \\
French & 0.85 & 0.85 & 0.85 & 0.85 \\
Japanese & 0.90 & 0.90 & 0.90 & 0.90 \\
Russian & 0.84 & 0.84 & 0.81 & 0.84 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
 & default_aya_old & prompt_aya_old & replace_aya_old & replace_morphology_aya_old \\
\midrule
Arabic & 0.84 & 0.85 & 0.84 & 0.85 \\
Chinese & 0.85 & 0.86 & 0.85 & 0.86 \\
French & 0.82 & 0.83 & 0.82 & 0.84 \\
Japanese & 0.88 & 0.88 & 0.88 & 0.89 \\
Russian & 0.82 & 0.82 & 0.80 & 0.83 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
 & default_aya & prompt_aya & replace_aya & replace_morphology_aya \\
\midrule
Arabic & 0.82 & 0.83 & 0.81 & 0.83 \\
Chinese & 0.83 & 0.85 & 0.84 & 0.85 \\
French & 0.82 & 0.83 & 0.82 & 0.83 \\
Japanese & 0.89 & 0.89 & 0.89 & 0.89 \\
Russian & 0.82 & 0.83 & 0.80 & 0.83 \\
\bottomrule
\end{tabular}

In [4]:
models = ['nllb', 'seamless', 'gpt4omini', 'aya_old', 'aya']
# exp_dict = {"default": "_comet", "prompt": "_prompt_gpt4omini_comet", "replace": "_hard_replace_comet"}
exp_dict = {"default": "_comet", "prompt": "_prompt_gpt4omini_comet", "replace": "_hard_replace_comet", "replace_morphology": "_hard_replace_morphology_comet"}
for model in models:
    dataframe_dict = {}
    for exp_name, exp_suffix in exp_dict.items():
        column_name = f"{exp_name}_{model}"
        dataframe_dict[column_name] = []
        
        data = json.load(open(f"/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/dataset/eval/{model}{exp_suffix}.json"))
        for lang in tgt_langs:
            dataframe_dict[column_name].append(data.get(f"{lang}_system_score", 0))  # Use `.get()` with default value `0` if lang not found

    # Create the DataFrame
    df = pd.DataFrame(dataframe_dict, index=tgt_langs)
    print(df.to_latex(float_format="%.2f"))

\begin{tabular}{lrrrr}
\toprule
 & default_nllb & prompt_nllb & replace_nllb & replace_morphology_nllb \\
\midrule
Arabic & 0.81 & 0.83 & 0.81 & 0.83 \\
Chinese & 0.80 & 0.82 & 0.81 & 0.83 \\
French & 0.79 & 0.83 & 0.77 & 0.80 \\
Japanese & 0.83 & 0.85 & 0.84 & 0.86 \\
Russian & 0.80 & 0.83 & 0.78 & 0.82 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
 & default_seamless & prompt_seamless & replace_seamless & replace_morphology_seamless \\
\midrule
Arabic & 0.82 & 0.83 & 0.82 & 0.84 \\
Chinese & 0.81 & 0.83 & 0.81 & 0.84 \\
French & 0.84 & 0.85 & 0.83 & 0.85 \\
Japanese & 0.84 & 0.85 & 0.84 & 0.86 \\
Russian & 0.83 & 0.85 & 0.81 & 0.85 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
 & default_gpt4omini & prompt_gpt4omini & replace_gpt4omini & replace_morphology_gpt4omini \\
\midrule
Arabic & 0.84 & 0.84 & 0.83 & 0.84 \\
Chinese & 0.86 & 0.86 & 0.86 & 0.86 \\
French & 0.85 & 0.85 & 0.84 & 0.85 \\
Japanese & 0.88 & 0.88 & 0.88 & 0.88 \\
Russian & 0.85 & 0.85 & 0.83 & 0.85 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
 & default_aya_old & prompt_aya_old & replace_aya_old & replace_morphology_aya_old \\
\midrule
Arabic & 0.82 & 0.83 & 0.81 & 0.83 \\
Chinese & 0.84 & 0.85 & 0.84 & 0.85 \\
French & 0.83 & 0.84 & 0.82 & 0.84 \\
Japanese & 0.84 & 0.85 & 0.84 & 0.86 \\
Russian & 0.83 & 0.84 & 0.81 & 0.84 \\
\bottomrule
\end{tabular}

\begin{tabular}{lrrrr}
\toprule
 & default_aya & prompt_aya & replace_aya & replace_morphology_aya \\
\midrule
Arabic & 0.81 & 0.81 & 0.80 & 0.82 \\
Chinese & 0.82 & 0.83 & 0.82 & 0.83 \\
French & 0.81 & 0.82 & 0.80 & 0.82 \\
Japanese & 0.85 & 0.86 & 0.86 & 0.86 \\
Russian & 0.83 & 0.83 & 0.81 & 0.84 \\
\bottomrule
\end{tabular}

# V1

In [1]:
import json
import pandas as pd

In [ ]:
tgt_langs = [
    "Chinese",
    "Arabic",
    "French",
    "Japanese",
    "Russian",
]

In [3]:
# data_g = json.load(open("/home/jiaruil5/multilingual/multilingual-model-card/src/data_eval_6060/eval/predictions_dev_googletrans_comet.json", 'r'))
data_g = json.load(open("/home/jiaruil5/multilingual/multilingual-model-card/src/data_eval_6060/eval/predictions_dev_googletrans_comet_noref_xl.json", 'r'))
data_g.keys()

dict_keys(['Chinese_scores', 'Chinese_system_score', 'Arabic_scores', 'Arabic_system_score', 'French_scores', 'French_system_score', 'Japanese_scores', 'Japanese_system_score', 'Russian_scores', 'Russian_system_score'])

In [4]:
# data_s = json.load(open("/home/jiaruil5/multilingual/multilingual-model-card/src/data_eval_6060/eval/predictions_dev_seamless_comet.json", 'r'))
data_s = json.load(open("/home/jiaruil5/multilingual/multilingual-model-card/src/data_eval_6060/eval/predictions_dev_seamless_comet_noref_xl.json", 'r'))
data_s.keys()

dict_keys(['Chinese_scores', 'Chinese_system_score', 'Arabic_scores', 'Arabic_system_score', 'French_scores', 'French_system_score', 'Japanese_scores', 'Japanese_system_score', 'Russian_scores', 'Russian_system_score'])

In [5]:
from collections import defaultdict
scores_dict = defaultdict(list)
for tgt_lang in tgt_langs:
    # print(f"{tgt_lang}_system_score", data[f"{tgt_lang}_system_score"])
    scores_dict[f"{tgt_lang}_system_score"].append(data_g[f"{tgt_lang}_system_score"])
    scores_dict[f"{tgt_lang}_system_score"].append(data_s[f"{tgt_lang}_system_score"])

In [11]:
# comet
scores_dict = dict(scores_dict)
df = pd.DataFrame(scores_dict)
df = df.T
df.columns = ['googletrans', 'seamless']
df

                       googletrans  seamless
Chinese_system_score      0.883238  0.838839
Arabic_system_score       0.875397  0.842705
French_system_score       0.847238  0.835571
Japanese_system_score     0.898531  0.850210
Russian_system_score      0.842348  0.819786

In [6]:
# comet_noref_xl
scores_dict = dict(scores_dict)
df = pd.DataFrame(scores_dict)
df = df.T
df.columns = ['googletrans', 'seamless']
df

                       googletrans  seamless
Chinese_system_score      0.697709  0.647375
Arabic_system_score       0.705548  0.675481
French_system_score       0.688482  0.673085
Japanese_system_score     0.756414  0.676290
Russian_system_score      0.706763  0.680274