In [1]:
import pandas as pd
from multilingualmc.evaluator.eval_on_6060_gold import get_mean_std_dict

In [2]:
# dataset_path = '/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/data_eval_6060/eval/gold_predictions_dev_'
dataset_path = '/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/dataset/eval/'

df_list = []
for model in ['nllb', 'seamless', 'gpt4omini', 'aya', 'aya_old']:
    df1 = pd.read_csv(f"{dataset_path}{model}.csv")
    res_g = get_mean_std_dict(df1)
    df2 = pd.read_csv(f"{dataset_path}{model}_prompt_gpt4omini.csv")
    res_s = get_mean_std_dict(df2)
    df3 = pd.read_csv(f"{dataset_path}{model}_hard_replace.csv")
    res_h = get_mean_std_dict(df3)
    df_g = pd.DataFrame.from_dict(res_g, orient='index')
    df_g.columns = [f'default_{model}']
    df_s = pd.DataFrame.from_dict(res_s, orient='index')
    df_s.columns = [f'prompt_{model}']
    df_h = pd.DataFrame.from_dict(res_h, orient='index')
    df_h.columns = [f'replace_{model}']
    df_list.extend([df_g, df_s, df_h])
df = pd.concat(df_list, axis=1)
pd.set_option('display.max_rows', None)
df

,default_nllb,prompt_nllb,replace_nllb,default_seamless,prompt_seamless,replace_seamless,default_gpt4omini,prompt_gpt4omini,replace_gpt4omini,default_aya,prompt_aya,replace_aya,default_aya_old,prompt_aya_old,replace_aya_old
Chinese_bleu_score_mean,10.242714,12.434321,12.311245,13.670800,14.767024,14.397723,17.213856,18.437501,18.601331,12.040152,12.983537,12.206943,14.503380,14.897192,14.697194
Chinese_bleu_score_std,11.679866,14.394978,13.708840,15.285313,15.792532,16.035155,18.755439,19.493859,19.249274,13.459609,14.415012,13.424830,15.361172,16.071713,15.519775
Chinese_bleu_1gram_precision_mean,10.291600,12.511687,12.376091,13.747659,14.857384,14.481115,17.349188,18.542179,18.702142,12.077673,13.029484,12.240863,14.582532,14.979879,14.775246
Chinese_bleu_1gram_precision_std,11.716468,14.447440,13.755332,15.307116,15.844228,16.080810,18.949378,19.622701,19.376625,13.511118,14.469232,13.463487,15.490775,16.195959,15.646165
Chinese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_ref_len_mean,75.920833,80.178000,79.388000,75.672340,81.096000,78.320000,83.213675,85.582000,85.496000,86.460000,86.230000,86.482000,84.040000,84.570000,84.064000
Chinese_bleu_ref_len_std,31.478325,32.633544,32.595189,34.877304,34.035564,33.848501,36.034992,35.240588,35.334502,36.212361,36.186406,36.241420,35.536123,35.277104,35.580160
Chinese_bleu_pred_len_mean,79.716667,84.074000,83.376000,78.804255,84.240000,81.608000,86.683761,88.986000,88.962000,92.340000,91.986000,92.374000,87.662000,88.194000,87.686000
Chinese_bleu_pred_len_std,34.398522,35.193546,35.407372,36.633376,35.877301,35.877859,37.806975,37.004005,37.096967,39.901838,39.678844,39.941065,37.738630,37.489456,37.809503
Chinese_bleu_bp_mean,0.983121,0.988634,0.987523,0.988255,0.991349,0.991186,0.994871,0.995101,0.995552,0.997611,0.997321,0.997630,0.995748,0.995740,0.995636
Chinese_bleu_bp_std,0.112088,0.079247,0.090425,0.053936,0.035904,0.039253,0.023482,0.020904,0.020252,0.014593,0.015546,0.014558,0.016880,0.016868,0.017033
Chinese_bleu_ratio_mean,1.044392,1.049157,1.050477,1.040781,1.038650,1.041355,1.039457,1.037837,1.038712,1.067658,1.067645,1.067772,1.041691,1.041475,1.041593
Chinese_bleu_ratio_std,0.142129,0.121411,0.129448,0.084048,0.070069,0.074338,0.059273,0.056303,0.056083,0.084695,0.089404,0.084557,0.064054,0.063421,0.064426
Chinese_chrf_score_mean,10.818115,13.078094,12.981049,14.335074,15.416832,15.059122,17.929379,19.155705,19.316707,12.764389,13.744460,12.942150,15.117807,15.517665,15.319583
Chinese_chrf_score_std,12.048005,14.822428,14.155486,15.650703,16.095755,16.379360,19.103667,19.821948,19.560853,13.861209,14.806861,13.831860,15.651691,16.349280,15.805402
Chinese_ter_score_mean,101.050254,98.596512,98.464688,97.259602,95.496428,96.192901,93.005075,90.776891,90.551394,99.335603,98.294132,99.127695,95.183775,94.489478,94.762121
Chinese_ter_score_std,19.343155,21.012149,19.971557,22.316460,21.458254,22.404142,24.890227,24.171000,24.001004,20.494251,21.515466,20.535763,20.333872,20.540301,20.074740
Chinese_chrfpp_score_mean,10.818115,13.078094,12.981049,14.335074,15.416832,15.059122,17.929379,19.155705,19.316707,12.764389,13.744460,12.942150,15.117807,15.517665,15.319583
Chinese_chrfpp_score_std,12.048005,14.822428,14.155486,15.650703,16.095755,16.379360,19.103667,19.821948,19.560853,13.861209,14.806861,13.831860,15.651691,16.349280,15.805402
Arabic_bleu_score_mean,15.422320,15.115546,14.656182,15.380512,16.475314,15.828079,14.369848,14.904206,13.948369,11.466253,11.831425,11.569323,14.276065,15.084099,14.552532
Arabic_bleu_score_std,15.757688,16.022553,14.645035,16.322209,17.523945,16.007964,16.316026,15.577164,14.301622,10.750150,11.919580,11.657750,14.759463,16.234804,15.037904
Arabic_bleu_1gram_precision_mean,15.538449,15.208924,14.759500,15.500843,16.579364,15.932719,14.420813,14.950095,13.996590,11.497554,11.861445,11.605224,14.343533,15.149451,14.625987
Arabic_bleu_1gram_precision_std,15.825797,16.064783,14.683071,16.398694,17.583733,16.063546,16.324274,15.590877,14.316620,10.777925,11.940562,11.688230,14.824631,16.293928,15.107723
Arabic_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_ref_len_mean,169.012500,177.836000,176.634000,173.421277,179.996000,179.570000,174.175214,181.134000,181.070000,183.006000,183.176000,183.274000,177.822000,179.164000,178.202000
Arabic_bleu_ref_len_std,65.197959,64.392374,63.908628,66.220536,64.012461,63.904685,67.357983,65.074060,65.154334,66.108931,66.206371,66.101572,65.994461,65.718940,66.072175
Arabic_bleu_pred_len_mean,168.720833,177.874000,176.632000,173.412766,179.914000,179.472000,174.264957,181.550000,181.374000,185.578000,185.770000,185.766000,178.212000,179.608000,178.542000
Arabic_bleu_pred_len_std,64.707074,64.405545,64.062318,66.224655,64.042560,63.990271,67.263608,65.193158,65.311234,66.509540,66.567948,66.439926,66.059631,65.784326,66.133922
Arabic_bleu_bp_mean,0.989220,0.991739,0.990807,0.991618,0.992903,0.992383,0.994984,0.996135,0.995607,0.997441,0.997463,0.997184,0.995205,0.995627,0.995032
Arabic_bleu_bp_std,0.027578,0.020209,0.020901,0.012440,0.010356,0.010778,0.010682,0.008342,0.009329,0.005647,0.005628,0.005837,0.010257,0.009614,0.010275
Arabic_bleu_ratio_mean,0.998364,1.000158,0.999760,0.999859,0.999734,0.999572,1.000744,1.002228,1.001460,1.017177,1.018181,1.016837,1.002958,1.003212,1.002627
Arabic_bleu_ratio_std,0.037576,0.032118,0.033689,0.026821,0.022139,0.023165,0.016178,0.014620,0.015151,0.045469,0.053311,0.046066,0.023662,0.022702,0.023418
Arabic_chrf_score_mean,15.953943,15.638617,15.181188,15.900145,17.004960,16.361428,14.822451,15.372945,14.404917,11.946944,12.315622,12.048075,14.772349,15.587452,15.054715
Arabic_chrf_score_std,16.000618,16.315065,14.925555,16.567444,17.758317,16.251184,16.465534,15.763233,14.489958,11.004080,12.150554,11.884715,15.023965,16.489904,15.293385
Arabic_ter_score_mean,101.291139,101.465461,101.998009,101.337129,99.860797,100.565534,102.333077,101.290215,102.579849,106.349068,106.046743,106.221271,102.453201,101.529420,102.085105
Arabic_ter_score_std,20.204467,20.060867,18.573230,21.115344,21.794658,19.972373,20.704111,19.205322,17.920084,15.124725,16.631409,15.957943,18.875750,20.353787,18.949221
Arabic_chrfpp_score_mean,15.953943,15.638617,15.181188,15.900145,17.004960,16.361428,14.822451,15.372945,14.404917,11.946944,12.315622,12.048075,14.772349,15.587452,15.054715
Arabic_chrfpp_score_std,16.000618,16.315065,14.925555,16.567444,17.758317,16.251184,16.465534,15.763233,14.489958,11.004080,12.150554,11.884715,15.023965,16.489904,15.293385
French_bleu_score_mean,22.676699,25.409439,23.574412,24.340755,29.549017,25.827921,24.447368,28.826841,25.728119,18.842562,20.556932,17.992064,24.492045,26.855476,24.567842
French_bleu_score_std,20.790924,23.064797,21.924062,20.936187,24.539429,21.798195,22.846905,26.474776,23.160010,18.048209,19.714995,16.230616,21.917871,23.527731,22.030290
French_bleu_1gram_precision_mean,22.745318,25.467822,23.642865,24.418770,29.603059,25.896787,24.510544,28.887303,25.794468,18.887741,20.599834,18.036380,24.581144,26.930499,24.653643
French_bleu_1gram_precision_std,20.828944,23.095459,21.958580,20.979822,24.565103,21.843128,22.880627,26.504987,23.191458,18.097175,19.754207,16.271382,21.957855,23.568915,22.068783
French_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_ref_len_mean,203.275000,234.126000,207.024000,237.170213,246.510000,243.298000,245.508547,252.038000,251.556000,252.308000,252.418000,252.402000,246.194000,249.560000,246.630000
French_bleu_ref_len_std,84.528717,89.519146,84.935714,90.054238,87.826721,87.191432,96.460548,91.076531,91.267115,91.641768,91.624261,91.681030,93.042712,90.928094,93.085288
French_bleu_pred_len_mean,204.825000,235.822000,208.574000,238.757447,248.142000,244.780000,245.923077,252.588000,251.948000,255.146000,255.250000,255.124000,246.416000,250.050000,246.798000
French_bleu_pred_len_std,85.310279,90.004867,85.730227,91.053548,88.536655,87.840375,96.659275,91.193678,91.329466,91.110257,91.184916,91.086498,92.992463,90.894902,92.960942
French_bleu_bp_mean,0.996218,0.997110,0.996085,0.994493,0.996677,0.996107,0.994976,0.996538,0.995959,0.997848,0.997911,0.997713,0.995581,0.996695,0.995741
French_bleu_bp_std,0.010639,0.008570,0.013029,0.030427,0.021473,0.021493,0.029967,0.020905,0.021128,0.005631,0.005734,0.005710,0.010049,0.007748,0.009176
French_bleu_ratio_mean,1.007955,1.008194,1.008155,1.004666,1.005795,1.005333,1.000447,1.001716,1.001174,1.016629,1.016434,1.016252,1.001459,1.002492,1.001427
French_bleu_ratio_std,0.026804,0.028487,0.033418,0.032340,0.024665,0.025483,0.028656,0.021189,0.021701,0.046377,0.046854,0.047058,0.019266,0.017501,0.018777
French_chrf_score_mean,23.334287,26.101968,24.247551,25.046990,30.297702,26.547358,25.037146,29.439160,26.346941,19.494838,21.232009,18.649611,25.113775,27.481370,25.181927
French_chrf_score_std,21.067160,23.287388,22.145730,21.092907,24.712801,22.029533,22.958551,26.588932,23.331541,18.374468,20.016782,16.584150,22.108194,23.672564,22.238683
French_ter_score_mean,91.400639,88.326638,90.507511,89.748448,83.276438,87.624699,89.155834,83.800526,87.359214,96.119341,94.099498,97.104412,89.068482,86.138371,88.791865
French_ter_score_std,25.515268,27.993737,26.907512,26.100498,29.478776,26.322800,27.900466,31.455940,27.520450,22.844704,24.644692,20.722881,26.619863,28.305063,26.493800
French_chrfpp_score_mean,23.334287,26.101968,24.247551,25.046990,30.297702,26.547358,25.037146,29.439160,26.346941,19.494838,21.232009,18.649611,25.113775,27.481370,25.181927
French_chrfpp_score_std,21.067160,23.287388,22.145730,21.092907,24.712801,22.029533,22.958551,26.588932,23.331541,18.374468,20.016782,16.584150,22.108194,23.672564,22.238683
Japanese_bleu_score_mean,8.242330,9.326088,9.125436,9.419722,9.984510,9.844065,10.548039,10.595776,10.578176,8.112657,8.083554,8.156257,9.216494,9.449407,9.565081
Japanese_bleu_score_std,10.823953,11.966811,11.648360,11.490450,12.778487,12.600689,12.865840,12.754156,12.823370,10.284407,10.118896,9.926873,12.229299,12.324542,12.836323
Japanese_bleu_1gram_precision_mean,8.326279,9.408287,9.215119,9.482488,10.030851,9.888231,10.580754,10.627815,10.608042,8.121997,8.092650,8.165596,9.250991,9.481094,9.598611
Japanese_bleu_1gram_precision_std,10.954650,12.102559,11.793046,11.542586,12.827062,12.642800,12.986894,12.847241,12.908203,10.292799,10.127463,9.935526,12.351135,12.438692,12.950113
Japanese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_ref_len_mean,108.204167,113.088000,112.404000,108.846809,112.646000,112.270000,116.508547,119.638000,120.026000,119.556000,119.588000,119.768000,114.144000,115.006000,114.242000
Japanese_bleu_ref_len_std,45.157789,43.784912,44.129941,45.862880,43.782994,44.249623,46.423988,44.575564,44.872535,46.725726,46.562801,46.715896,46.741210,46.438206,46.637856
Japanese_bleu_pred_len_mean,112.329167,117.012000,116.402000,113.565957,117.390000,117.194000,121.098291,124.692000,125.098000,126.608000,126.634000,126.848000,120.256000,121.016000,120.358000
Japanese_bleu_pred_len_std,47.458019,46.188989,46.721839,47.701338,45.754922,46.513130,48.275352,46.613590,46.938458,48.798082,48.635861,48.799300,49.410862,48.963646,49.292244
Japanese_bleu_bp_mean,0.989053,0.992007,0.990671,0.990872,0.995228,0.993120,0.997664,0.997785,0.997850,0.998636,0.998648,0.998636,0.996937,0.996869,0.996952
Japanese_bleu_bp_std,0.073252,0.049967,0.054787,0.048580,0.025186,0.041077,0.009203,0.008566,0.008544,0.009735,0.009733,0.009735,0.020356,0.020592,0.020561
Japanese_bleu_ratio_mean,1.033888,1.032792,1.032779,1.045134,1.043160,1.043312,1.039451,1.041943,1.041925,1.064291,1.064142,1.064398,1.056392,1.055483,1.056397
Japanese_bleu_ratio_std,0.102798,0.083021,0.086802,0.092337,0.068664,0.075961,0.045338,0.046619,0.046362,0.073995,0.073977,0.074008,0.084516,0.084294,0.084575
Japanese_chrf_score_mean,8.605812,9.717522,9.533592,9.908371,10.457363,10.318296,10.991946,11.054105,11.025315,8.591330,8.574438,8.653056,9.681781,9.932771,10.048230
Japanese_chrf_score_std,11.036710,12.297695,11.967636,11.907528,13.189525,12.990532,13.175537,13.044518,13.106227,10.696138,10.549627,10.347825,12.476165,12.604258,13.092047
Japanese_ter_score_mean,101.405200,100.095018,100.542436,100.586841,99.238653,99.439075,98.393990,98.319437,98.268905,101.989787,101.962812,101.917053,100.300980,99.867642,99.716647
Japanese_ter_score_std,16.926324,16.765657,16.690754,18.727175,17.225437,17.195266,18.101101,17.189126,17.312664,16.221148,15.808942,15.794801,17.734900,17.260433,17.755492
Japanese_chrfpp_score_mean,8.605812,9.717522,9.533592,9.908371,10.457363,10.318296,10.991946,11.054105,11.025315,8.591330,8.574438,8.653056,9.681781,9.932771,10.048230
Japanese_chrfpp_score_std,11.036710,12.297695,11.967636,11.907528,13.189525,12.990532,13.175537,13.044518,13.106227,10.696138,10.549627,10.347825,12.476165,12.604258,13.092047
Russian_bleu_score_mean,19.175503,19.074097,18.937335,18.430775,19.381420,18.779894,18.021742,19.541687,18.426035,13.844962,14.057661,14.165962,16.391939,17.755388,17.005338
Russian_bleu_score_std,19.820571,19.234276,19.061278,17.902535,18.506610,17.457347,19.690356,20.967095,19.567886,13.568655,14.077806,13.260314,17.611531,18.407246,18.366436
Russian_bleu_1gram_precision_mean,19.242196,19.132891,19.000263,18.475603,19.437149,18.835635,18.125701,19.622974,18.508525,13.887174,14.098812,14.212089,16.474647,17.835977,17.090059
Russian_bleu_1gram_precision_std,19.822261,19.247675,19.074060,17.919274,18.538670,17.489086,19.723986,21.001521,19.599771,13.607152,14.118359,13.311659,17.686760,18.479352,18.447028
Russian_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_ref_len_mean,195.837500,220.604000,200.928000,222.395745,231.720000,229.590000,230.393162,236.140000,236.372000,238.174000,238.010000,238.422000,232.808000,234.376000,233.016000
Russian_bleu_ref_len_std,83.602583,84.776798,84.414848,84.522545,83.391522,82.203508,90.658957,85.390113,85.337228,87.007680,87.125654,87.092561,88.094725,86.951018,88.034766
Russian_bleu_pred_len_mean,196.937500,221.806000,202.154000,223.387234,232.744000,230.602000,230.149573,236.192000,236.328000,240.602000,240.406000,240.790000,232.904000,234.612000,233.116000
Russian_bleu_pred_len_std,84.711918,85.633373,85.454920,85.503780,84.228019,83.096966,90.885859,85.822784,85.721320,86.857677,87.007043,86.898980,88.377690,87.212760,88.266962
Russian_bleu_bp_mean,0.994965,0.996049,0.995737,0.994481,0.995465,0.995231,0.992719,0.994616,0.994287,0.997249,0.997380,0.997144,0.993890,0.994477,0.993974
Russian_bleu_bp_std,0.032158,0.023526,0.023700,0.033213,0.024562,0.024562,0.036497,0.026229,0.026340,0.007174,0.007112,0.007279,0.024878,0.024596,0.024829
Russian_bleu_ratio_mean,1.003713,1.004400,1.004902,1.001849,1.002669,1.002530,0.996996,0.998598,0.998216,1.013766,1.013514,1.013522,0.999205,0.999826,0.999280
Russian_bleu_ratio_std,0.032862,0.028734,0.029425,0.032297,0.025808,0.026416,0.032780,0.024630,0.024827,0.040065,0.037825,0.040574,0.026028,0.025683,0.026054
Russian_chrf_score_mean,19.631649,19.562212,19.434236,18.883276,19.857538,19.255381,18.435604,19.951251,18.830799,14.318715,14.527959,14.661091,16.775873,18.161431,17.396623

In [7]:
df[df.index.str.startswith('Russian')]

,default_nllb,prompt_nllb,replace_nllb,default_seamless,prompt_seamless,replace_seamless,default_gpt4omini,prompt_gpt4omini,replace_gpt4omini,default_aya,prompt_aya,replace_aya,default_aya_old,prompt_aya_old,replace_aya_old
Russian_bleu_score_mean,19.175503,19.074097,18.937335,18.430775,19.381420,18.779894,18.021742,19.541687,18.426035,13.844962,14.057661,14.165962,16.391939,17.755388,17.005338
Russian_bleu_score_std,19.820571,19.234276,19.061278,17.902535,18.506610,17.457347,19.690356,20.967095,19.567886,13.568655,14.077806,13.260314,17.611531,18.407246,18.366436
Russian_bleu_1gram_precision_mean,19.242196,19.132891,19.000263,18.475603,19.437149,18.835635,18.125701,19.622974,18.508525,13.887174,14.098812,14.212089,16.474647,17.835977,17.090059
Russian_bleu_1gram_precision_std,19.822261,19.247675,19.074060,17.919274,18.538670,17.489086,19.723986,21.001521,19.599771,13.607152,14.118359,13.311659,17.686760,18.479352,18.447028
Russian_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_ref_len_mean,195.837500,220.604000,200.928000,222.395745,231.720000,229.590000,230.393162,236.140000,236.372000,238.174000,238.010000,238.422000,232.808000,234.376000,233.016000
Russian_bleu_ref_len_std,83.602583,84.776798,84.414848,84.522545,83.391522,82.203508,90.658957,85.390113,85.337228,87.007680,87.125654,87.092561,88.094725,86.951018,88.034766
Russian_bleu_pred_len_mean,196.937500,221.806000,202.154000,223.387234,232.744000,230.602000,230.149573,236.192000,236.328000,240.602000,240.406000,240.790000,232.904000,234.612000,233.116000
Russian_bleu_pred_len_std,84.711918,85.633373,85.454920,85.503780,84.228019,83.096966,90.885859,85.822784,85.721320,86.857677,87.007043,86.898980,88.377690,87.212760,88.266962
Russian_bleu_bp_mean,0.994965,0.996049,0.995737,0.994481,0.995465,0.995231,0.992719,0.994616,0.994287,0.997249,0.997380,0.997144,0.993890,0.994477,0.993974
Russian_bleu_bp_std,0.032158,0.023526,0.023700,0.033213,0.024562,0.024562,0.036497,0.026229,0.026340,0.007174,0.007112,0.007279,0.024878,0.024596,0.024829
Russian_bleu_ratio_mean,1.003713,1.004400,1.004902,1.001849,1.002669,1.002530,0.996996,0.998598,0.998216,1.013766,1.013514,1.013522,0.999205,0.999826,0.999280
Russian_bleu_ratio_std,0.032862,0.028734,0.029425,0.032297,0.025808,0.026416,0.032780,0.024630,0.024827,0.040065,0.037825,0.040574,0.026028,0.025683,0.026054
Russian_chrf_score_mean,19.631649,19.562212,19.434236,18.883276,19.857538,19.255381,18.435604,19.951251,18.830799,14.318715,14.527959,14.661091,16.775873,18.161431,17.396623
Russian_chrf_score_std,19.959102,19.442484,19.282317,18.035867,18.680479,17.622396,19.833543,21.101541,19.698200,13.829595,14.307529,13.544846,17.752461,18.541539,18.502631
Russian_ter_score_mean,93.260302,93.535087,93.634359,94.151697,93.121951,93.773771,94.395559,92.582250,93.887958,99.767971,99.582718,99.369902,96.280917,94.554735,95.437202
Russian_ter_score_std,24.108758,23.064772,22.851044,22.056053,22.292151,21.142318,23.669533,24.650881,23.348436,17.184890,17.634421,16.796557,21.392375,21.915299,21.927132
Russian_chrfpp_score_mean,19.631649,19.562212,19.434236,18.883276,19.857538,19.255381,18.435604,19.951251,18.830799,14.318715,14.527959,14.661091,16.775873,18.161431,17.396623
Russian_chrfpp_score_std,19.959102,19.442484,19.282317,18.035867,18.680479,17.622396,19.833543,21.101541,19.698200,13.829595,14.307529,13.544846,17.752461,18.541539,18.502631

papers+model_cards

In [10]:
dataset_path = "/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/dataset/eval/"

df_list = []
for model in ['nllb', 'seamless', 'gpt4omini', 'aya', 'aya_old']:
    df1 = pd.read_csv(f"{dataset_path}{model}.csv")
    res_g = get_mean_std_dict(df1)
    df2 = pd.read_csv(f"{dataset_path}{model}_prompt_gpt4omini.csv")
    res_s = get_mean_std_dict(df2)
    df3 = pd.read_csv(f"{dataset_path}{model}_hard_replace.csv")
    res_h = get_mean_std_dict(df3)
    df_g = pd.DataFrame.from_dict(res_g, orient='index')
    df_g.columns = [f'default_{model}']
    df_s = pd.DataFrame.from_dict(res_s, orient='index')
    df_s.columns = [f'prompt_{model}']
    df_h = pd.DataFrame.from_dict(res_h, orient='index')
    df_h.columns = [f'replace_{model}']
    df_list.extend([df_g, df_s, df_h])
df = pd.concat(df_list, axis=1)
pd.set_option('display.max_rows', None)
df

,default_nllb,prompt_nllb,replace_nllb,default_seamless,prompt_seamless,replace_seamless,default_gpt4omini,prompt_gpt4omini,replace_gpt4omini,default_aya,prompt_aya,replace_aya,default_aya_old,prompt_aya_old,replace_aya_old
Chinese_bleu_score_mean,10.242714,12.434321,12.311245,13.670800,14.767024,14.397723,17.213856,18.437501,18.601331,12.040152,12.983537,12.206943,14.503380,14.897192,14.697194
Chinese_bleu_score_std,11.679866,14.394978,13.708840,15.285313,15.792532,16.035155,18.755439,19.493859,19.249274,13.459609,14.415012,13.424830,15.361172,16.071713,15.519775
Chinese_bleu_1gram_precision_mean,10.291600,12.511687,12.376091,13.747659,14.857384,14.481115,17.349188,18.542179,18.702142,12.077673,13.029484,12.240863,14.582532,14.979879,14.775246
Chinese_bleu_1gram_precision_std,11.716468,14.447440,13.755332,15.307116,15.844228,16.080810,18.949378,19.622701,19.376625,13.511118,14.469232,13.463487,15.490775,16.195959,15.646165
Chinese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_ref_len_mean,75.920833,80.178000,79.388000,75.672340,81.096000,78.320000,83.213675,85.582000,85.496000,86.460000,86.230000,86.482000,84.040000,84.570000,84.064000
Chinese_bleu_ref_len_std,31.478325,32.633544,32.595189,34.877304,34.035564,33.848501,36.034992,35.240588,35.334502,36.212361,36.186406,36.241420,35.536123,35.277104,35.580160
Chinese_bleu_pred_len_mean,79.716667,84.074000,83.376000,78.804255,84.240000,81.608000,86.683761,88.986000,88.962000,92.340000,91.986000,92.374000,87.662000,88.194000,87.686000
Chinese_bleu_pred_len_std,34.398522,35.193546,35.407372,36.633376,35.877301,35.877859,37.806975,37.004005,37.096967,39.901838,39.678844,39.941065,37.738630,37.489456,37.809503
Chinese_bleu_bp_mean,0.983121,0.988634,0.987523,0.988255,0.991349,0.991186,0.994871,0.995101,0.995552,0.997611,0.997321,0.997630,0.995748,0.995740,0.995636
Chinese_bleu_bp_std,0.112088,0.079247,0.090425,0.053936,0.035904,0.039253,0.023482,0.020904,0.020252,0.014593,0.015546,0.014558,0.016880,0.016868,0.017033
Chinese_bleu_ratio_mean,1.044392,1.049157,1.050477,1.040781,1.038650,1.041355,1.039457,1.037837,1.038712,1.067658,1.067645,1.067772,1.041691,1.041475,1.041593
Chinese_bleu_ratio_std,0.142129,0.121411,0.129448,0.084048,0.070069,0.074338,0.059273,0.056303,0.056083,0.084695,0.089404,0.084557,0.064054,0.063421,0.064426
Chinese_chrf_score_mean,10.818115,13.078094,12.981049,14.335074,15.416832,15.059122,17.929379,19.155705,19.316707,12.764389,13.744460,12.942150,15.117807,15.517665,15.319583
Chinese_chrf_score_std,12.048005,14.822428,14.155486,15.650703,16.095755,16.379360,19.103667,19.821948,19.560853,13.861209,14.806861,13.831860,15.651691,16.349280,15.805402
Chinese_ter_score_mean,101.050254,98.596512,98.464688,97.259602,95.496428,96.192901,93.005075,90.776891,90.551394,99.335603,98.294132,99.127695,95.183775,94.489478,94.762121
Chinese_ter_score_std,19.343155,21.012149,19.971557,22.316460,21.458254,22.404142,24.890227,24.171000,24.001004,20.494251,21.515466,20.535763,20.333872,20.540301,20.074740
Chinese_chrfpp_score_mean,10.818115,13.078094,12.981049,14.335074,15.416832,15.059122,17.929379,19.155705,19.316707,12.764389,13.744460,12.942150,15.117807,15.517665,15.319583
Chinese_chrfpp_score_std,12.048005,14.822428,14.155486,15.650703,16.095755,16.379360,19.103667,19.821948,19.560853,13.861209,14.806861,13.831860,15.651691,16.349280,15.805402
Arabic_bleu_score_mean,15.422320,15.115546,14.656182,15.380512,16.475314,15.828079,14.369848,14.904206,13.948369,11.466253,11.831425,11.569323,14.276065,15.084099,14.552532
Arabic_bleu_score_std,15.757688,16.022553,14.645035,16.322209,17.523945,16.007964,16.316026,15.577164,14.301622,10.750150,11.919580,11.657750,14.759463,16.234804,15.037904
Arabic_bleu_1gram_precision_mean,15.538449,15.208924,14.759500,15.500843,16.579364,15.932719,14.420813,14.950095,13.996590,11.497554,11.861445,11.605224,14.343533,15.149451,14.625987
Arabic_bleu_1gram_precision_std,15.825797,16.064783,14.683071,16.398694,17.583733,16.063546,16.324274,15.590877,14.316620,10.777925,11.940562,11.688230,14.824631,16.293928,15.107723
Arabic_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_ref_len_mean,169.012500,177.836000,176.634000,173.421277,179.996000,179.570000,174.175214,181.134000,181.070000,183.006000,183.176000,183.274000,177.822000,179.164000,178.202000
Arabic_bleu_ref_len_std,65.197959,64.392374,63.908628,66.220536,64.012461,63.904685,67.357983,65.074060,65.154334,66.108931,66.206371,66.101572,65.994461,65.718940,66.072175
Arabic_bleu_pred_len_mean,168.720833,177.874000,176.632000,173.412766,179.914000,179.472000,174.264957,181.550000,181.374000,185.578000,185.770000,185.766000,178.212000,179.608000,178.542000
Arabic_bleu_pred_len_std,64.707074,64.405545,64.062318,66.224655,64.042560,63.990271,67.263608,65.193158,65.311234,66.509540,66.567948,66.439926,66.059631,65.784326,66.133922
Arabic_bleu_bp_mean,0.989220,0.991739,0.990807,0.991618,0.992903,0.992383,0.994984,0.996135,0.995607,0.997441,0.997463,0.997184,0.995205,0.995627,0.995032
Arabic_bleu_bp_std,0.027578,0.020209,0.020901,0.012440,0.010356,0.010778,0.010682,0.008342,0.009329,0.005647,0.005628,0.005837,0.010257,0.009614,0.010275
Arabic_bleu_ratio_mean,0.998364,1.000158,0.999760,0.999859,0.999734,0.999572,1.000744,1.002228,1.001460,1.017177,1.018181,1.016837,1.002958,1.003212,1.002627
Arabic_bleu_ratio_std,0.037576,0.032118,0.033689,0.026821,0.022139,0.023165,0.016178,0.014620,0.015151,0.045469,0.053311,0.046066,0.023662,0.022702,0.023418
Arabic_chrf_score_mean,15.953943,15.638617,15.181188,15.900145,17.004960,16.361428,14.822451,15.372945,14.404917,11.946944,12.315622,12.048075,14.772349,15.587452,15.054715
Arabic_chrf_score_std,16.000618,16.315065,14.925555,16.567444,17.758317,16.251184,16.465534,15.763233,14.489958,11.004080,12.150554,11.884715,15.023965,16.489904,15.293385
Arabic_ter_score_mean,101.291139,101.465461,101.998009,101.337129,99.860797,100.565534,102.333077,101.290215,102.579849,106.349068,106.046743,106.221271,102.453201,101.529420,102.085105
Arabic_ter_score_std,20.204467,20.060867,18.573230,21.115344,21.794658,19.972373,20.704111,19.205322,17.920084,15.124725,16.631409,15.957943,18.875750,20.353787,18.949221
Arabic_chrfpp_score_mean,15.953943,15.638617,15.181188,15.900145,17.004960,16.361428,14.822451,15.372945,14.404917,11.946944,12.315622,12.048075,14.772349,15.587452,15.054715
Arabic_chrfpp_score_std,16.000618,16.315065,14.925555,16.567444,17.758317,16.251184,16.465534,15.763233,14.489958,11.004080,12.150554,11.884715,15.023965,16.489904,15.293385
French_bleu_score_mean,22.676699,25.409439,23.574412,24.340755,29.549017,25.827921,24.447368,28.826841,25.728119,18.842562,20.556932,17.992064,24.492045,26.855476,24.567842
French_bleu_score_std,20.790924,23.064797,21.924062,20.936187,24.539429,21.798195,22.846905,26.474776,23.160010,18.048209,19.714995,16.230616,21.917871,23.527731,22.030290
French_bleu_1gram_precision_mean,22.745318,25.467822,23.642865,24.418770,29.603059,25.896787,24.510544,28.887303,25.794468,18.887741,20.599834,18.036380,24.581144,26.930499,24.653643
French_bleu_1gram_precision_std,20.828944,23.095459,21.958580,20.979822,24.565103,21.843128,22.880627,26.504987,23.191458,18.097175,19.754207,16.271382,21.957855,23.568915,22.068783
French_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_ref_len_mean,203.275000,234.126000,207.024000,237.170213,246.510000,243.298000,245.508547,252.038000,251.556000,252.308000,252.418000,252.402000,246.194000,249.560000,246.630000
French_bleu_ref_len_std,84.528717,89.519146,84.935714,90.054238,87.826721,87.191432,96.460548,91.076531,91.267115,91.641768,91.624261,91.681030,93.042712,90.928094,93.085288
French_bleu_pred_len_mean,204.825000,235.822000,208.574000,238.757447,248.142000,244.780000,245.923077,252.588000,251.948000,255.146000,255.250000,255.124000,246.416000,250.050000,246.798000
French_bleu_pred_len_std,85.310279,90.004867,85.730227,91.053548,88.536655,87.840375,96.659275,91.193678,91.329466,91.110257,91.184916,91.086498,92.992463,90.894902,92.960942
French_bleu_bp_mean,0.996218,0.997110,0.996085,0.994493,0.996677,0.996107,0.994976,0.996538,0.995959,0.997848,0.997911,0.997713,0.995581,0.996695,0.995741
French_bleu_bp_std,0.010639,0.008570,0.013029,0.030427,0.021473,0.021493,0.029967,0.020905,0.021128,0.005631,0.005734,0.005710,0.010049,0.007748,0.009176
French_bleu_ratio_mean,1.007955,1.008194,1.008155,1.004666,1.005795,1.005333,1.000447,1.001716,1.001174,1.016629,1.016434,1.016252,1.001459,1.002492,1.001427
French_bleu_ratio_std,0.026804,0.028487,0.033418,0.032340,0.024665,0.025483,0.028656,0.021189,0.021701,0.046377,0.046854,0.047058,0.019266,0.017501,0.018777
French_chrf_score_mean,23.334287,26.101968,24.247551,25.046990,30.297702,26.547358,25.037146,29.439160,26.346941,19.494838,21.232009,18.649611,25.113775,27.481370,25.181927
French_chrf_score_std,21.067160,23.287388,22.145730,21.092907,24.712801,22.029533,22.958551,26.588932,23.331541,18.374468,20.016782,16.584150,22.108194,23.672564,22.238683
French_ter_score_mean,91.400639,88.326638,90.507511,89.748448,83.276438,87.624699,89.155834,83.800526,87.359214,96.119341,94.099498,97.104412,89.068482,86.138371,88.791865
French_ter_score_std,25.515268,27.993737,26.907512,26.100498,29.478776,26.322800,27.900466,31.455940,27.520450,22.844704,24.644692,20.722881,26.619863,28.305063,26.493800
French_chrfpp_score_mean,23.334287,26.101968,24.247551,25.046990,30.297702,26.547358,25.037146,29.439160,26.346941,19.494838,21.232009,18.649611,25.113775,27.481370,25.181927
French_chrfpp_score_std,21.067160,23.287388,22.145730,21.092907,24.712801,22.029533,22.958551,26.588932,23.331541,18.374468,20.016782,16.584150,22.108194,23.672564,22.238683
Japanese_bleu_score_mean,8.242330,9.326088,9.125436,9.419722,9.984510,9.844065,10.548039,10.595776,10.578176,8.112657,8.083554,8.156257,9.216494,9.449407,9.565081
Japanese_bleu_score_std,10.823953,11.966811,11.648360,11.490450,12.778487,12.600689,12.865840,12.754156,12.823370,10.284407,10.118896,9.926873,12.229299,12.324542,12.836323
Japanese_bleu_1gram_precision_mean,8.326279,9.408287,9.215119,9.482488,10.030851,9.888231,10.580754,10.627815,10.608042,8.121997,8.092650,8.165596,9.250991,9.481094,9.598611
Japanese_bleu_1gram_precision_std,10.954650,12.102559,11.793046,11.542586,12.827062,12.642800,12.986894,12.847241,12.908203,10.292799,10.127463,9.935526,12.351135,12.438692,12.950113
Japanese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_ref_len_mean,108.204167,113.088000,112.404000,108.846809,112.646000,112.270000,116.508547,119.638000,120.026000,119.556000,119.588000,119.768000,114.144000,115.006000,114.242000
Japanese_bleu_ref_len_std,45.157789,43.784912,44.129941,45.862880,43.782994,44.249623,46.423988,44.575564,44.872535,46.725726,46.562801,46.715896,46.741210,46.438206,46.637856
Japanese_bleu_pred_len_mean,112.329167,117.012000,116.402000,113.565957,117.390000,117.194000,121.098291,124.692000,125.098000,126.608000,126.634000,126.848000,120.256000,121.016000,120.358000
Japanese_bleu_pred_len_std,47.458019,46.188989,46.721839,47.701338,45.754922,46.513130,48.275352,46.613590,46.938458,48.798082,48.635861,48.799300,49.410862,48.963646,49.292244
Japanese_bleu_bp_mean,0.989053,0.992007,0.990671,0.990872,0.995228,0.993120,0.997664,0.997785,0.997850,0.998636,0.998648,0.998636,0.996937,0.996869,0.996952
Japanese_bleu_bp_std,0.073252,0.049967,0.054787,0.048580,0.025186,0.041077,0.009203,0.008566,0.008544,0.009735,0.009733,0.009735,0.020356,0.020592,0.020561
Japanese_bleu_ratio_mean,1.033888,1.032792,1.032779,1.045134,1.043160,1.043312,1.039451,1.041943,1.041925,1.064291,1.064142,1.064398,1.056392,1.055483,1.056397
Japanese_bleu_ratio_std,0.102798,0.083021,0.086802,0.092337,0.068664,0.075961,0.045338,0.046619,0.046362,0.073995,0.073977,0.074008,0.084516,0.084294,0.084575
Japanese_chrf_score_mean,8.605812,9.717522,9.533592,9.908371,10.457363,10.318296,10.991946,11.054105,11.025315,8.591330,8.574438,8.653056,9.681781,9.932771,10.048230
Japanese_chrf_score_std,11.036710,12.297695,11.967636,11.907528,13.189525,12.990532,13.175537,13.044518,13.106227,10.696138,10.549627,10.347825,12.476165,12.604258,13.092047
Japanese_ter_score_mean,101.405200,100.095018,100.542436,100.586841,99.238653,99.439075,98.393990,98.319437,98.268905,101.989787,101.962812,101.917053,100.300980,99.867642,99.716647
Japanese_ter_score_std,16.926324,16.765657,16.690754,18.727175,17.225437,17.195266,18.101101,17.189126,17.312664,16.221148,15.808942,15.794801,17.734900,17.260433,17.755492
Japanese_chrfpp_score_mean,8.605812,9.717522,9.533592,9.908371,10.457363,10.318296,10.991946,11.054105,11.025315,8.591330,8.574438,8.653056,9.681781,9.932771,10.048230
Japanese_chrfpp_score_std,11.036710,12.297695,11.967636,11.907528,13.189525,12.990532,13.175537,13.044518,13.106227,10.696138,10.549627,10.347825,12.476165,12.604258,13.092047
Russian_bleu_score_mean,19.175503,19.074097,18.937335,18.430775,19.381420,18.779894,18.021742,19.541687,18.426035,13.844962,14.057661,14.165962,16.391939,17.755388,17.005338
Russian_bleu_score_std,19.820571,19.234276,19.061278,17.902535,18.506610,17.457347,19.690356,20.967095,19.567886,13.568655,14.077806,13.260314,17.611531,18.407246,18.366436
Russian_bleu_1gram_precision_mean,19.242196,19.132891,19.000263,18.475603,19.437149,18.835635,18.125701,19.622974,18.508525,13.887174,14.098812,14.212089,16.474647,17.835977,17.090059
Russian_bleu_1gram_precision_std,19.822261,19.247675,19.074060,17.919274,18.538670,17.489086,19.723986,21.001521,19.599771,13.607152,14.118359,13.311659,17.686760,18.479352,18.447028
Russian_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_ref_len_mean,195.837500,220.604000,200.928000,222.395745,231.720000,229.590000,230.393162,236.140000,236.372000,238.174000,238.010000,238.422000,232.808000,234.376000,233.016000
Russian_bleu_ref_len_std,83.602583,84.776798,84.414848,84.522545,83.391522,82.203508,90.658957,85.390113,85.337228,87.007680,87.125654,87.092561,88.094725,86.951018,88.034766
Russian_bleu_pred_len_mean,196.937500,221.806000,202.154000,223.387234,232.744000,230.602000,230.149573,236.192000,236.328000,240.602000,240.406000,240.790000,232.904000,234.612000,233.116000
Russian_bleu_pred_len_std,84.711918,85.633373,85.454920,85.503780,84.228019,83.096966,90.885859,85.822784,85.721320,86.857677,87.007043,86.898980,88.377690,87.212760,88.266962
Russian_bleu_bp_mean,0.994965,0.996049,0.995737,0.994481,0.995465,0.995231,0.992719,0.994616,0.994287,0.997249,0.997380,0.997144,0.993890,0.994477,0.993974
Russian_bleu_bp_std,0.032158,0.023526,0.023700,0.033213,0.024562,0.024562,0.036497,0.026229,0.026340,0.007174,0.007112,0.007279,0.024878,0.024596,0.024829
Russian_bleu_ratio_mean,1.003713,1.004400,1.004902,1.001849,1.002669,1.002530,0.996996,0.998598,0.998216,1.013766,1.013514,1.013522,0.999205,0.999826,0.999280
Russian_bleu_ratio_std,0.032862,0.028734,0.029425,0.032297,0.025808,0.026416,0.032780,0.024630,0.024827,0.040065,0.037825,0.040574,0.026028,0.025683,0.026054
Russian_chrf_score_mean,19.631649,19.562212,19.434236,18.883276,19.857538,19.255381,18.435604,19.951251,18.830799,14.318715,14.527959,14.661091,16.775873,18.161431,17.396623

In [ ]:
df[df.index.str.startswith('Russian')]