In [2]:
import json
import numpy as np
import pandas as pd
data = json.load(open("mturk.json", 'r'))
df = pd.DataFrame().from_records(data)
df

,English,context,Arabic,Chinese,French,Japanese,Russian
0,10-fold cross validation,"1: For all the methods, we used <mark>10-fold ...",التحقق المتقاطع بمقدار ١٠ أضعاف,十折交叉验证,validation croisée 10 fois,10分割交差検証,10-кратная перекрестная проверка
1,1D convolution,1: In addition to the usual quadratic kernels ...,1D الإلتواء,1D 卷积,Convolution 1D,1次元畳み込み,одномерная свертка
2,2 norm,"1: To alleviate this limitation, we proposed a...",معيار 2,2范数,norme 2,2ノルム,2 норма
3,2D convolution,1: Adding 3D convolutions to <mark>2D convolut...,الإلتواء 2D,二维卷积,convolution 2D,2D畳み込み,2D свертка
4,2D image,"1: Here x is the feature computed by a layer, ...",صورة ثنائية الأبعاد,二维图像,image 2D,2次元画像,2D изображение
...,...,...,...,...,...,...,...
4713,zero-shot transfer,"1: Dufter and Schütze (2020) found that, after...","- Candidate term translation 2: ""- تحويل بدون ...",零次迁移,transfert sans apprentissage,ゼロショット転移,Перенос без предварительного обучения
4714,zero-shot transfer learning,1: (10) Since the estimate given by s (tnew ) ...,التعلم النقلي بدون تدريب,零样本迁移学习,apprentissage par transfert zéro,ゼロショット転移学習,обучение с нулевым переносом
4715,Zipf,"1: But, we want to ensure that our dataset mat...",قانون زيف,齐普夫分布,loi de Zipf,ジップフ,закон Ципфа
4716,Zipf distribution,1: Skewed distributions appear very often in p...,توزيع زيبف,Zipf分布,distribution de Zipf,ジップ分布,распределение Ципфа
4717,Zipf's law,1: Lemma 1. The Discrete Gaussian Exponential ...,قانون زيبف,Zipf定律,Loi de Zipf,ジプフの法則,закон Ципфа

In [10]:
# Creating interleaved sub-dataframes from the original DataFrame.
# Split the DataFrame into 5 sub-dataframes interleavingly.

# Create empty sub-dataframes
interleaved_sub_dfs = [df.iloc[i::5].reset_index(drop=True) for i in range(5)]

# Add suffixes to each interleaved sub-dataframe
suffixes = ['1', '2', '3', '4', '5']
interleaved_sub_dfs = [sub_df.add_suffix(suffix) for sub_df, suffix in zip(interleaved_sub_dfs, suffixes)]

# Concatenate the interleaved sub-dataframes by columns
interleaved_concat_df = pd.concat(interleaved_sub_dfs, axis=1)

interleaved_concat_df

,English1,context1,Arabic1,Chinese1,French1,Japanese1,Russian1,English2,context2,Arabic2,...,French4,Japanese4,Russian4,English5,context5,Arabic5,Chinese5,French5,Japanese5,Russian5
0,10-fold cross validation,"1: For all the methods, we used <mark>10-fold ...",التحقق المتقاطع بمقدار ١٠ أضعاف,十折交叉验证,validation croisée 10 fois,10分割交差検証,10-кратная перекрестная проверка,1D convolution,1: In addition to the usual quadratic kernels ...,1D الإلتواء,...,convolution 2D,2D畳み込み,2D свертка,2D image,"1: Here x is the feature computed by a layer, ...",صورة ثنائية الأبعاد,二维图像,image 2D,2次元画像,2D изображение
1,2D image synthesis,1: Neural Image Synthesis. Deep models for 2D ...,تخليق صور ثنائية الأبعاد,二维图像合成,synthèse d'images 2D,2次元画像合成,синтез 2D-изображений,2D-3D correspondence,"1: To summarize, our main contributions are as...",المراسلات ثنائية وثلاثية الأبعاد,...,Vision par ordinateur 3D,3次元コンピュータビジョン,трехмерное компьютерное зрение,3D convolutional network,1: The choice of architecture proves to be imp...,شبكة تلافيفية ثلاثية الأبعاد,三维卷积网络,réseau convolutionnel 3D,3次元畳み込みネットワーク,трёхмерная сверточная сеть
2,3D geometry,1: To that end we define an energy function th...,هندسة ثلاثية الأبعاد,三维几何,géométrie 3D,3次元ジオメトリ,3D геометрия,3D human pose estimation,1: Existing diffusion-based pose estimation ap...,تقدير وضعية الإنسان ثلاثي الأبعاد,...,maillage 3D,3次元メッシュ,3D сетка,3D model,1: The 3D flow algorithm of §6 was initialized...,نموذج ثلاثي الأبعاد,三维模型,modèle 3D,3Dモデル,3D-модель
3,3D object detection,"1: Estimating the pose (i.e., position and ori...",اكتشاف الكائنات ثلاثية الأبعاد,三维目标检测,détection d'objets 3D,3次元物体検出,обнаружение 3D-объектов,3D point,1: An analogous warping is used for non-rigid ...,نقطة ثلاثية الأبعاد,...,pose 3D,3次元ポーズ,3D поза,3D reconstruction,1: Minimal problems arise from geometrical pro...,إعادة الإعمار ثلاثية الأبعاد,三维重建,reconstruction 3D,3D再構築,Трехмерная реконструкция
4,3D scene,1: Since most current scene understanding appr...,المشهد ثلاثي الأبعاد,三维场景,scène 3D,3次元シーン,трёхмерная сцена,3D scene geometry,"1: However, exhaustive sampling of the light f...",هندسة المشهد ثلاثية الأبعاد,...,Validation croisée à 5 volets,5分割交差検証,5-кратная перекрестная проверка,Adafactor,1: Model We evaluate the efficiency of our pro...,أدافاكتور,Adafactor,Adafactor,アダファクタ,Адафактор
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,word token,1: In order to verify that semantic informatio...,رمز الكلمة,词标记,jeton de mot,単語トークン,токен слова,word vector,1: We show that retrofitting gives consistent ...,متجه الكلمة,...,corpus aligné par mot,単語アラインメントコーパス,корпус с выравниванием слов,word-level,"1: We introduce OpenKiwi, a PyTorch-based open...",على مستوى الكلمة,单词级别,au niveau des mots,単語レベル,на уровне слов
940,word-level vocabulary,"1: Byte-Pair Encoding (BPE) (Sennrich et al., ...",المفردات على مستوى الكلمة,词级词汇表,vocabulaire au niveau des mots,単語レベルの語彙,словарь на уровне слов,word2vec embedding,1: The use of lexical semantic information in ...,تضمين word2vec,...,score z,Zスコア,Значение Z,zero-one loss,"1: Second, we prove the case that is not the <...",خسارة صفر واحد,0-1损失,perte zéro-un,ゼロワン損失,потеря ноль-единица
941,zero-shot classification,1: For ImageNet <mark>zero-shot classification...,تصنيف صفر طلقة,零样本分类,Classification sans entraînement,ゼロショット分類,классификация без предварительной подготовки,zero-shot cross-lingual setting,1: Cross-lingual Question Answering Languagesp...,الإعداد عبر اللغات بدون تدريب,...,"""apprentissage sans tir""",ゼロショット学習,обучение с нулевым выстрелом,zero-shot prediction,"1: For ChatGPT, we slightly modify the prompts...",التنبؤ بدون تدريب,零样本预测,prédiction sans exemple,ゼロショット予測,предсказание с нулевой разметкой
942,zero-shot prompting,1: The complete list of results for <mark>zero...,استدعاء من دون إعطاء مثال,零样本提示,sollicitation zéro-shot,ゼロショットプロンプティング,нулевая генерация подсказок,zero-shot reasoning,"1: We also add ""Let's think step by step"" befo...",الاستدلال بدون تدريب,...,transfert sans apprentissage,ゼロショット転移,Перенос без предварительного обучения,zero-shot transfer learning,1: (10) Since the estimate given by s (tnew ) ...,التعلم النقلي بدون تدريب,零样本迁移学习,apprentissage par transfert zéro,ゼロショット転移学習,обучение с нулевым переносом
943,Zipf,"1: But, we want to ensure that our dataset mat...",قانون زيف,齐普夫分布,loi de Zipf,ジップフ,закон Ципфа,Zipf distribution,1: Skewed distributions appear very often in p...,توزيع زيبف,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
interleaved_concat_df.to_csv("mturk_5terms_per_page.csv")

In [16]:
interleaved_concat_df.sample(5).reset_index(drop=True).to_csv("test_5terms_per_page.csv")

In [19]:
interleaved_concat_df.sample(5).reset_index(drop=True).to_csv("test_5terms.csv")

In [20]:
import pandas as pd
df = pd.read_csv("test_5terms_per_page.csv")
df

,Unnamed: 0,English1,context1,Arabic1,Chinese1,French1,Japanese1,Russian1,English2,context2,...,French4,Japanese4,Russian4,English5,context5,Arabic5,Chinese5,French5,Japanese5,Russian5
0,0,constituency parser,1: Kitaev and Klein (2020) were the first to p...,محلل تشكيليات,短语结构分析器,analyseur syntaxique par constituants,構成素パーサー,синтаксический анализатор составляющих,constituency parsing,1: We start with a linear-time vine pruning pa...,...,analyse syntaxique en constituants,構成素解析,составной синтаксический разбор,constituent structure,"1: As in TAG approaches, there is a mapping fr...",البنية المكونة,成分结构,structure constituante,構成構造,составляющая структура
1,1,text mining,1: Statistical topic modeling has attracted mu...,تنقيب النصوص,文本挖掘,fouille de texte,テキストマイニング,текстовый анализ,text segmentation,1: We make our implementation of A publicly av...,...,résumé de texte,テキスト要約,Реферирование текста,text-davinci-002,"1: On stimuli containing distraction (i.e., bo...",نص دافينشي-002,文本-​​达芬奇-002,text-davinci-002,テキスト-ダヴィンチ-002,текст-давинчи-002
2,2,word alignment,"1: In this paper, we work with IBM Model 4, wh...",مُواءَمَةُ الكَلِمَات,词对齐,alignement de mots,単語アライメント,выравнивание слов,word dropout,1: 7 We also apply <mark>word dropout</mark> (...,...,modèle de plongements lexicaux,ワード埋め込みモデル,модель векторного представления слов,Word Mover's Distance,1: Quantitative Model Performance Metrics. We ...,مسافة محرك الكلمات,词移距离,distance de déplacement de mots,ワードムーバー距離,расстояние перемещения слова
3,3,convolutional network,1: A cluster of similar approaches based on co...,شبكة تلافيفية,卷积网络,réseau convolutionnel,畳み込みネットワーク,сверточная сеть,convolutional neural net,"1: • X: (x t , x t+1 ) ∈ (R height×width×3 ) 2...",...,représentation convolutionnelle,畳み込み表現,сверточное представление,cooling schedule,"1: c T } is the schedule of annealing ""tempera...",جدول التبريد,冷却进度表,programme de refroidissement,冷却スケジュール,график охлаждения
4,4,attention model,1: Conditioning the GAN model on these AUs all...,نموذج الانتباه,注意力模型,modèle d'attention,注意モデル,модель внимания,attention module,"1: However, we made some important modificatio...",...,modèle d'attention,アテンションパターン,схема внимания,attention score,1: where L(x) is the loss function of example ...,درجة الانتباه,注意力分数,score d'attention,注意スコア,оценка внимания

In [7]:
sub_dfs = np.array_split(df, 5)

# Add suffixes to column names for each sub-dataframe
suffixes = ['1', '2', '3', '4', '5']
sub_dfs = [sub_df.add_suffix(suffix) for sub_df, suffix in zip(sub_dfs, suffixes)]

# Concatenate the sub-dataframes by columns
concat_df = pd.concat(sub_dfs, axis=1)

/data/user_data/jiaruil5/miniconda3/envs/new/lib/python3.11/site-packages/numpy/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes' is deprecated and will be removed in a future version. Please use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)

In [8]:
sub_dfs[1]

,English2,context2,Arabic2,Chinese2,French2,Japanese2,Russian2
944,confidence bound,"1: In practice, since the <mark>confidence bou...",إرتباط الثقة,置信绑定,borne de confiance,信頼度束縛,доверительная связь
945,confidence interval,"1: Overall, we observe length can influence LM...",فترة الثقة,置信区间,intervalle de confiance,信頼区間,доверительный интервал
946,confidence map,"1: We use a special layer, called Voting layer...",خريطة الثقة,置信度映射图,carte de confiance,信頼度マップ,карта уверенности
947,confidence score,"1: 9, we can find that the pseudo targets achi...",مستوى الثقة,置信度分数,score de confiance,信頼度スコア,показатель уверенности
948,confidence threshold,"1: Once this is done, the algorithm then appli...",عتبة الثقة,置信度阈值,seuil de confiance,信頼度閾値,порог уверенности
...,...,...,...,...,...,...,...
1883,gradient penalty,"1: The observer (the camera in our case), in c...","- Candidate term translation 1: ""عقوبة التدرج""",梯度惩罚,pénalité de gradient,勾配ペナルティ,градиентное наказание
1884,gradient signal,"1: AutoPrompt (Shin et al., 2020) searches for...",إشارة التدرج,梯度信号,signal de gradient,勾配シグナル,сигнал градиента
1885,gradient step,"1: Training is performed in batch mode, with a...",خطوة التدرج,梯度步长,pas de gradient,勾配ステップ,шаг градиента
1886,gradient term,1: We use a multi-scale <mark>gradient term</m...,مصطلح التدرج,梯度项,terme de gradient,勾配項,градиентный член
1887,gradient update,1: : fully unroll the recurrent part of the ac...,تحديث التدرج,梯度更新,mise à jour du gradient,勾配更新,градиентное обновление

In [9]:
concat_df

,English1,context1,Arabic1,Chinese1,French1,Japanese1,Russian1,English2,context2,Arabic2,...,French4,Japanese4,Russian4,English5,context5,Arabic5,Chinese5,French5,Japanese5,Russian5
0,10-fold cross validation,"1: For all the methods, we used <mark>10-fold ...",التحقق المتقاطع بمقدار ١٠ أضعاف,十折交叉验证,validation croisée 10 fois,10分割交差検証,10-кратная перекрестная проверка,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1D convolution,1: In addition to the usual quadratic kernels ...,1D الإلتواء,1D 卷积,Convolution 1D,1次元畳み込み,одномерная свертка,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2 norm,"1: To alleviate this limitation, we proposed a...",معيار 2,2范数,norme 2,2ノルム,2 норма,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2D convolution,1: Adding 3D convolutions to <mark>2D convolut...,الإلتواء 2D,二维卷积,convolution 2D,2D畳み込み,2D свертка,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2D image,"1: Here x is the feature computed by a layer, ...",صورة ثنائية الأبعاد,二维图像,image 2D,2次元画像,2D изображение,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4713,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,zero-shot transfer,"1: Dufter and Schütze (2020) found that, after...","- Candidate term translation 2: ""- تحويل بدون ...",零次迁移,transfert sans apprentissage,ゼロショット転移,Перенос без предварительного обучения
4714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,zero-shot transfer learning,1: (10) Since the estimate given by s (tnew ) ...,التعلم النقلي بدون تدريب,零样本迁移学习,apprentissage par transfert zéro,ゼロショット転移学習,обучение с нулевым переносом
4715,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Zipf,"1: But, we want to ensure that our dataset mat...",قانون زيف,齐普夫分布,loi de Zipf,ジップフ,закон Ципфа
4716,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Zipf distribution,1: Skewed distributions appear very often in p...,توزيع زيبف,Zipf分布,distribution de Zipf,ジップ分布,распределение Ципфа
4717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Zipf's law,1: Lemma 1. The Discrete Gaussian Exponential ...,قانون زيبف,Zipf定律,Loi de Zipf,ジプフの法則,закон Ципфа